DonationAcademy/DonationAcademy/Areas/Admin/Controllers/AdminImagensController.cs
using DonationAcademy.Models;
using Microsoft.AspNetCore.Authorization;
using System.Data;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Options;

namespace DonationAcademy.Areas.Admin.Controllers
{
    [Area("Admin")]
    [Authorize(Roles = RolesTypes.Admin + "," + RolesTypes.Vendedor + "," + RolesTypes.Gerente)]
    public class AdminImagensController : Controller
    {
        private readonly ConfigurationImagens _myConfig;
        private readonly IWebHostEnvironment _hostingEnvironment;

        public AdminImagensController(IWebHostEnvironment hostingEnvironment,
            IOptions<ConfigurationImagens> myConfiguration)
        {
            _hostingEnvironment = hostingEnvironment;
            _myConfig = myConfiguration.Value;
        }

        public IActionResult Index()
        {
            return View();
        }

        public async Task<IActionResult> UploadFiles(List<IFormFile> files)
        {
            if (files == null || files.Count == 0)
            {
                ViewData["Erro"] = "Error: Arquivo(s) não selecionado(s)";
                return View(ViewData);
            }

            if (files.Count > 10)
            {
                ViewData["Erro"] = "Error: Quantidade de arquivos excedeu o limite";
                return View(ViewData);
            }

            long size = files.Sum(f => f.Length);

            var filePathsName = new List<string>();

            var filePath = Path.Combine(_hostingEnvironment.WebRootPath, _myConfig.NomePastaImagensProdutos);

            foreach (var formFile in files)
            {
                if (formFile.FileName.EndsWith(".jpg", StringComparison.OrdinalIgnoreCase) ||
                    formFile.FileName.EndsWith(".jpeg", StringComparison.OrdinalIgnoreCase) ||
                    formFile.FileName.EndsWith(".gif", StringComparison.OrdinalIgnoreCase) ||
                    formFile.FileName.EndsWith(".png", StringComparison.OrdinalIgnoreCase))
                {
                    var fileNameWithPath = Path.Combine(filePath, formFile.FileName);
                    filePathsName.Add(fileNameWithPath);

                    using (var stream = new FileStream(fileNameWithPath, FileMode.Create))
                    {
                        await formFile.CopyToAsync(stream);
                    }
                }
            }

            ViewData["Resultado"] = $"{filePathsName.Count} arquivos foram enviados ao servidor, com tamanho total de {size} bytes";
            ViewBag.Arquivos = filePathsName;

            return View(ViewData);
        }

        public IActionResult GetImagens()
        {
            var model = new FileManagerModel();
            var userImagesPath = Path.Combine(_hostingEnvironment.WebRootPath, _myConfig.NomePastaImagensProdutos);

            if (!Directory.Exists(userImagesPath))
            {
                ViewData["Erro"] = $"Pasta {userImagesPath} não encontrada";
                return View(model);
            }

            var files = new DirectoryInfo(userImagesPath).GetFiles();

            model.PathImagesProduto = _myConfig.NomePastaImagensProdutos;

            if (files.Length == 0)
            {
                ViewData["Erro"] = $"Nenhum arquivo encontrado na pasta {userImagesPath}";
            }

            model.Files = files;

            return View(model);
        }

        public IActionResult Deletefile(string fname)
        {
            var userImagesPath = Path.Combine(_hostingEnvironment.WebRootPath, _myConfig.NomePastaImagensProdutos);
            var fileNameWithPath = Path.Combine(userImagesPath, fname);

            if (System.IO.File.Exists(fileNameWithPath))
            {
                System.IO.File.Delete(fileNameWithPath);
                ViewData["Deletado"] = $"Arquivo {fname} deletado com sucesso";
            }

            return View("Index");
        }

    }
}

DonationAcademy/DonationAcademy/Areas/Admin/Views/AdminImagens/GetImagens.cshtml
@model FileManagerModel

@*Area de admin*@

@{
    ViewBag.Title = "Arquivos";
}

<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <style>
        h3 {
            margin-top: 30px;
        }

        a {
            color: white;
        }

        button[onclick] {
            background-color: cornflowerblue;
            color: white;
            border: none;
            padding: 10px;
            border-radius: 5px;
            font-size: 14px;
            height: 50px;
            margin-top: 18px;
        }

            button[onclick]:hover {
                box-shadow: 0px 0px 5px black;
            }
    </style>

</head>

<body>
    @if (Model.Files != null)
    {
        <h3>Imagens: </h3>
        <hr />
        var caminho = Model.PathImagesProduto;

        <div class="row">
            @foreach (FileInfo file in Model.Files)
            {
                <div class="col-2">
                    <img src="~/@caminho/@file.Name" width="125" height="125" title="@file.Name" asp-append-version="true">
                    <div style="padding:10px;text-align:left">
                        <a href="@Url.Action("Deletefile","AdminImagens",new { fname=file.Name})">Deletar</a>

                        <button onclick="copyToClipboard('@Model.PathImagesProduto/@file.Name')">Copiar caminho da imagem</button>

                    </div>
                </div>
            }


        </div>



    }
    <script src="~/js/site.js"></script>

</body>

</html>

DonationAcademy/DonationAcademy/Areas/Admin/Views/AdminImagens/Index.cshtml
<style>
    .col-md-10 {
        margin-top: 30px;
    }
</style>

<table border="0" width="100%">
    <tr>
        <td>
            <form method="post" enctype="multipart/form-data" asp-controller="AdminImagens" asp-action="UploadFiles">

                <div class="form-group">
                    <div class="col-md-10">
                        <img src="~/images/folder.png" />
                        <br />
                        <p><b>Selecione um ou mais arquivos para enviar :</b></p>
                        <p>(Arquivos com o mesmo nome serão sobrescritos)</p>
                        <input type="file" name="files" multiple class="button btn-outline-primary" />
                    </div>
                </div>

                <hr />
                <div class="form-group">
                    <div class="col-md-10">

                        <input style="color:black" type="submit" value="Enviar Arquivo (s)" class="button btn-outline-primary" />

                    </div>
                </div>
            </form>


        </td>

        <td>
            <form method="post" enctype="multipart/form-data" asp-controller="AdminImagens" asp-action="GetImagens">

                <div class="form-group">
                    <div class="col-md-10">
                        <img src="~/images/search.png" />
                        <p><strong>Visualizar Imagens na pasta do servidor :</strong></p>
                    </div>
                </div>
                <hr />
                <div class="form-group">
                    <div class="col-md-10">
                        <input style="color: black" type="submit" value="Visualizar Arquivos no servidor" class="button btn-outline-secondary" />
                    </div>
                </div>


            </form>
        </td>
    </tr>
</table>

<div class="container">
    @if (ViewData["Deletado"] != null)
    {
        <ul>
            <li>@ViewData["Deletado"]</li>
        </ul>
    }
</div>

DonationAcademy/DonationAcademy/Areas/Admin/Views/AdminImagens/UploadFiles.cshtml
@{
    ViewData["Title"] = "UploadFiles";
}

<style>
    img {
        margin-top: 30px;
    }
</style>
<img src="~/images/folder.png" />
<hr />

<div class="jumbotron jumbotron-fluid">
    <div class="container">

        @if (ViewData["Erro"] != null)
        {
            @*<img src="~/images/erro" width="150" height="150" />*@
            <h4>@ViewData["Erro"]</h4>
        }

    </div>

    <div class="container">
        @if (ViewData["Resultado"] != null)
        {
            <h4>@ViewData["Resultado"]</h4>
            <hr />
            @if (ViewBag.Arquivos != null)
            {
                @foreach (string arquivo in ViewBag.Arquivos)
                {
                    <ul>
                        <li>@arquivo</li>
                    </ul>
                }
            }
        }
    </div>

</div>