DonationAcademy/DonationAcademy/Models/CarrinhoCompra.cs
using System.ComponentModel.DataAnnotations;

using DonationAcademy.Context;
using DonationAcademy.Migrations;

using Microsoft.EntityFrameworkCore;

namespace DonationAcademy.Models
{
    //SingleOrDefault --> Método alternativo para adicionar ou remover itens
   // do carrinho
    public class CarrinhoCompra
    {
        private readonly AppDbContext _context;

        public CarrinhoCompra(AppDbContext context)
        {
            _context = context;
        }

        [Key]
        public string CarrinhoCompraId { get; set; }
        public List<CarrinhoCompraItem> CarrinhoCompraItems { get; set; }

        public static CarrinhoCompra GetCarrinho(IServiceProvider services)
        {
            //define uma sessão
            ISession session =
                services.GetRequiredService<IHttpContextAccessor>()?.HttpContext.Session;

            //obtem um serviço do tipo do nosso contexto 
            var context = services.GetService<AppDbContext>();

            //obtem ou gera o Id do carrinho
            string carrinhoId = session.GetString("CarrinhoId") ?? Guid.NewGuid().ToString();

            //atribui o id do carrinho na Sessão
            session.SetString("CarrinhoId", carrinhoId);

            //retorna o carrinho com o contexto e o Id atribuido ou obtido
            return new CarrinhoCompra(context)
            {
                CarrinhoCompraId = carrinhoId
            };
        }

        public void AdicionarAoCarrinho(Material material)
        {
            var carrinhoCompraItem = _context.CarrinhoCompraItens.SingleOrDefault(

                s => s.Material.MaterialId == material.MaterialId &&
                s.CarrinhoCompraId == CarrinhoCompraId);


            if (carrinhoCompraItem == null)
            {
                carrinhoCompraItem = new CarrinhoCompraItem
                {
                    CarrinhoCompraId = CarrinhoCompraId,
                    Material = material,
                    Quantidade = 1

                };

                _context.CarrinhoCompraItens.Add(carrinhoCompraItem);
            }
            else
            {
                carrinhoCompraItem.Quantidade++;
            }

            _context.SaveChanges();
        }


        public int RemoverDoCarrinho(Material material)
        {
            var carrinhoCompraItem = _context.CarrinhoCompraItens.FirstOrDefault(

               s => s.Material.MaterialId == material.MaterialId &&
               s.CarrinhoCompraId == CarrinhoCompraId);


            var quantidadeLocal = 0;

            if (carrinhoCompraItem != null)
            {
                if (carrinhoCompraItem.Quantidade > 1)
                {
                    carrinhoCompraItem.Quantidade--;
                    quantidadeLocal = carrinhoCompraItem.Quantidade;

                }
                else
                {
                    _context.CarrinhoCompraItens.Remove(carrinhoCompraItem);
                }
            }

            _context.SaveChanges();
            return quantidadeLocal;
        }

        public List<CarrinhoCompraItem> GetCarrinhoCompraItens()
        {
            return CarrinhoCompraItems ??
                   (CarrinhoCompraItems =
                       _context.CarrinhoCompraItens.Where(c => c.CarrinhoCompraId == CarrinhoCompraId)
                           .Include(s => s.Material)
                           .ToList());
        }

        public void LimparCarrinho()
        {
            var carrinhoItens = _context.CarrinhoCompraItens
                                 .Where(carrinho => carrinho.CarrinhoCompraId == CarrinhoCompraId);

            _context.CarrinhoCompraItens.RemoveRange(carrinhoItens);
            _context.SaveChanges();
        }

        public decimal GetCarrinhoCompraTotal()
        {
            var total = _context.CarrinhoCompraItens
                           .Where(c => c.CarrinhoCompraId == CarrinhoCompraId)
                           .Select(c => c.Material.Preco * c.Quantidade).Sum();

            return total;
        }
    }
}

DonationAcademy/DonationAcademy/ViewModels/CarrinhoCompraViewModel.cs
using DonationAcademy.Models;

namespace DonationAcademy.ViewModels
{
    public class CarrinhoCompraViewModel
    {
        public CarrinhoCompra CarrinhoCompra { get; set; }
        public decimal CarrinhoCompraTotal { get; set; }
    }
}

DonationAcademy/DonationAcademy/Controllers/CarrinhoCompraController.cs
using DonationAcademy.Models;
using DonationAcademy.Repositories.Interfaces;
using DonationAcademy.ViewModels;

using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace DonationAcademy.Controllers
{
    [Authorize]
    public class CarrinhoCompraController : Controller
    {
        private readonly IMaterialRepository _materialRepository;
        private readonly CarrinhoCompra _carrinhoCompra;

        public CarrinhoCompraController(IMaterialRepository materialRepository, CarrinhoCompra carrinhoCompra)
        {
            _materialRepository = materialRepository;
            _carrinhoCompra = carrinhoCompra;
        }

        [Authorize]
        public IActionResult Carrinho()
        {
            var itens = _carrinhoCompra.GetCarrinhoCompraItens();
            _carrinhoCompra.CarrinhoCompraItems = itens;

            var carrinhoCompraVM = new CarrinhoCompraViewModel
            {
                CarrinhoCompra = _carrinhoCompra,
                CarrinhoCompraTotal = _carrinhoCompra.GetCarrinhoCompraTotal(),

            };
            return View(carrinhoCompraVM);
        }

        [Authorize]
        public RedirectToActionResult AdicionarItemNoCarrinhoCompra(int materialId)
        {
            var materialSelecionado = _materialRepository.Materiais
                .FirstOrDefault(m => 
                m.MaterialId == materialId);

            if (materialSelecionado != null)
            {
                _carrinhoCompra.AdicionarAoCarrinho(materialSelecionado);
            }

            return RedirectToAction("Carrinho");
        }

        [Authorize]
        public IActionResult RemoverItemDoCarrinho(int materialId)
        {
            var materialSelecionado = _materialRepository.Materiais
                .FirstOrDefault(m =>
                m.MaterialId == materialId);

            if (materialSelecionado != null)
            {
                _carrinhoCompra.RemoverDoCarrinho(materialSelecionado);
            }

            return RedirectToAction("Carrinho");
        }
    }
}

DonationAcademy/DonationAcademy/Controllers/PedidoController.cs
using DonationAcademy.Models;
using DonationAcademy.Repositories.Interfaces;

using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace DonationAcademy.Controllers
{
    [Authorize]
    public class PedidoController : Controller
    {
        private readonly IPedidoRepository _pedidoRepository;
        private readonly CarrinhoCompra _carrinhoCompra;

        public PedidoController(IPedidoRepository pedidoRepository, CarrinhoCompra carrinhoCompra)
        {
            _pedidoRepository = pedidoRepository;
            _carrinhoCompra = carrinhoCompra;
        }

        [Authorize]
        [HttpGet]
        public IActionResult Checkout()
        {
            return View();
        }
        [Authorize]
        [HttpPost]
        public IActionResult Checkout(Pedido pedido)
        {
            int totalItensPedido = 0;
            decimal precoTotalPedido = 0.0m;

            // obtém os itens de compra do cliente

            List<CarrinhoCompraItem> itens = _carrinhoCompra.GetCarrinhoCompraItens();
            _carrinhoCompra.CarrinhoCompraItems = itens;

            //Verifica se existe itens de pedido

            if (_carrinhoCompra.CarrinhoCompraItems.Count == 0)
            {
                ModelState.AddModelError("", "Ops! Seu carrinho está vazio! Que tal incluir um produto?");
            }

            //Caso tenha itens no carrinho: Calcular o total de itens e o total do pedido
            foreach (var item in itens)
            {
                totalItensPedido += item.Quantidade;
                precoTotalPedido += (item.Material.Preco * item.Quantidade);
            }

            // atribui os valores obtidos ao pedido
            pedido.TotalItensPedido = totalItensPedido;
            pedido.PedidoTotal = precoTotalPedido;

            //valida os dados do pedido
            if (ModelState.IsValid)
            {
                // cria o pedido e seus respectivos detalhes
                _pedidoRepository.CriarPedido(pedido);

                //define mensagens ao cliente
                ViewBag.CheckoutCompletoMensagem = "\nPedido realizado com sucesso! Obrigado por visitar o nosso site :)\n";
                ViewBag.TotalPedido = _carrinhoCompra.GetCarrinhoCompraTotal();

                //limpa o carrinho do cliente
                _carrinhoCompra.LimparCarrinho();

                //exibe a view com dados do cliente e do pedido

                return View("~/Views/Pedido/CheckoutCompleto.cshtml", pedido);
            }

            return View(pedido);
        }
    }
}

DonationAcademy/DonationAcademy/Views/CarrinhoCompra/Carrinho.cshtml
@model CarrinhoCompraViewModel

<!DOCTYPE html>
<html lang="pt-br">
<head>
    <meta charset="utf-8" />
    <style>
        .table {
            background-color: white;
        }
    </style>
</head>
<body>
    

    <div class="container">
        
        <div class="row">

            <img style="height:13vh; width: 13vh" src="~/images/cart2.png" />

            <div>
                <h4>Seu carrinho de compras</h4>
            </div>

            <table class="table table-bordered table-striped">
                <thead>
                    <tr>
                        <th>Quantidade</th>
                        <th>Material</th>
                        <th class="text-right">Preço</th>
                        <th class="text-right">Subtotal</th>
                        <th></th>
                    </tr>
                </thead>


                <tbody>
                    @foreach (var item in Model.CarrinhoCompra.CarrinhoCompraItems)
                    {
                        <tr>
                            <td class="text-center">@item.Quantidade</td>
                            <td class="text-left">@item.Material.Nome</td>
                            <td class="text-right">@item.Material.Preco.ToString("c")</td>

                            <td class="text-right">
                                @((item.Quantidade * item.Material.Preco).ToString("c"))
                            </td>



                            <th class="text-center">
                                <a asp-controller="CarrinhoCompra" asp-action="RemoverItemDoCarrinho" asp-route-materialId="@item.Material.MaterialId">
                                    <img src="~/images/trash.svg" />
                                </a>
                            </th>


                        </tr>
                    }
                </tbody>

                <tfoot>
                    <tr>
                        <td colspan="3" class="text-right">Total:</td>
                        <td class="text-right">
                            @Model.CarrinhoCompraTotal.ToString("c")
                        </td>
                    </tr>
                </tfoot>

            </table>

            <div class="text-right">
                <div class="btn-group">
                    <a class="btn btn-success" asp-controller="Pedido" asp-action="Checkout">Encerrar Pedido</a>
                    &nbsp;&nbsp;&nbsp;
                    <a class="btn btn-primary" asp-controller="Material" asp-action="List">Continuar Comprando</a>
                </div>
            </div>

            <br />
        </div>
    </div>
</body>
</html>