DonationAcademy/DonationAcademy/Areas/Admin/Controllers/AdminUsuariosController.cs
using DonationAcademy.Models;
using Microsoft.AspNetCore.Authorization;
using System.Data;

using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using DonationAcademy.Context;
using Microsoft.AspNetCore.Identity;
using ReflectionIT.Mvc.Paging;
using DonationAcademy.Areas.Admin.ViewModels;
using System.Text;


namespace DonationAcademy.Areas.Admin.Controllers
{
    [Area("Admin")]
    [Authorize(Roles = RolesTypes.Admin)]
    public class AdminUsuariosController : Controller
    {
        private readonly UserManager<IdentityUser> _userManager;
        private readonly SignInManager<IdentityUser> _signInManager;
        private readonly RoleManager<IdentityRole> _roleManager;
        private readonly AppDbContext _context;

        public AdminUsuariosController(UserManager<IdentityUser> userManager, 
            SignInManager<IdentityUser> signInManager, 
            RoleManager<IdentityRole> roleManager, 
            AppDbContext context)
        {
            _userManager = userManager;
            _signInManager = signInManager;
            _roleManager = roleManager;
            _context = context;
        }


        // GET: AdminUsuariosController
        public async Task<IActionResult> Index(string filter, int pageindex = 1)
        {
            var usersQuery = _context.Users.AsQueryable();
            if (!string.IsNullOrWhiteSpace(filter))
            {
                usersQuery = usersQuery.Where(u => u.Email.Contains(filter));
                usersQuery = usersQuery.Where(u => u.UserName.Contains(filter));

            }
            

            var viewModelList = new List<AdminRegistroUsuarioViewModel>();
            foreach (var user in usersQuery)
            {
                var viewModel = new AdminRegistroUsuarioViewModel
                {
                    Id = user.Id,
                    UserName = user.UserName,
                    EmailRegister = user.Email,
                    IsAdmin = await _userManager.IsInRoleAsync(user, RolesTypes.Admin),
                    IsGerente = await _userManager.IsInRoleAsync(user, RolesTypes.Gerente),
                    IsVendedor = await _userManager.IsInRoleAsync(user, RolesTypes.Vendedor),
                    IsDoador = await _userManager.IsInRoleAsync(user, RolesTypes.AreaDoacao)
                };
                viewModelList.Add(viewModel);
            }
            var lista = viewModelList.AsQueryable();
            var model = PagingList.Create(lista, 5, pageindex);

            model.RouteValue = new RouteValueDictionary { { "filter", filter } };
            model.Action = "Index";
            return View(model);
        }

        // GET: AdminFuncionariosController/Details/5
        public async Task<IActionResult> Details(string id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var user = await _userManager.FindByIdAsync(id);

            if (user == null)
            {
                return NotFound();
            }

            var userRoles = await _userManager.GetRolesAsync(user);
            var viewModel = new AdminRegistroUsuarioViewModel
            {
                Id = user.Id,
                UserName = user.UserName,
                EmailRegister = user.Email,
                IsAdmin = userRoles.Contains(RolesTypes.Admin),
                IsGerente = userRoles.Contains(RolesTypes.Gerente),
                IsVendedor = userRoles.Contains(RolesTypes.Vendedor),
                IsDoador = userRoles.Contains(RolesTypes.AreaDoacao)
            };

            return View("Details", viewModel);
        }


        // GET: AdminFuncionariosController/Create
        public IActionResult Create()
        {
            return View(new AdminRegistroUsuarioViewModel());
        }

        // POST: AdminUsuariosController/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(AdminRegistroUsuarioViewModel model)
        {
            if (ModelState.IsValid)
            {
                var userExists = await _userManager.FindByNameAsync(model.UserName);
                if (userExists != null)
                {
                    ModelState.AddModelError("", "Já existe um usuário com esse nome.");
                    return View(model);
                }

                userExists = await _userManager.FindByEmailAsync(model.EmailRegister);
                if (userExists != null)
                {
                    ModelState.AddModelError("", "Já existe um usuário com esse e-mail.");
                    return View(model);
                }


                var user = new IdentityUser { UserName = model.UserName, Email = model.EmailRegister };
                var result = await _userManager.CreateAsync(user, model.GeneratedPassword);

                if (result.Succeeded)
                {
                    if (model.IsVendedor)
                    {
                        await _userManager.AddToRoleAsync(user, RolesTypes.Vendedor);
                    }
                    if (model.IsGerente)
                    {
                        await _userManager.AddToRoleAsync(user, RolesTypes.Gerente);
                    }
                    if (model.IsAdmin)
                    {
                        await _userManager.AddToRoleAsync(user, RolesTypes.Admin);
                    }
                    if (model.IsDoador)
                    {
                        await _userManager.AddToRoleAsync(user, RolesTypes.AreaDoacao);
                    }

                    return RedirectToAction(nameof(Index));
                }
                else
                {
                    foreach (var error in result.Errors)
                    {
                        ModelState.AddModelError("", error.Description);
                    }
                }
            }
            return View(model);
        }


        // GET: AdminFuncionariosController/Edit/5
        public async Task<IActionResult> Edit(string id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var user = await _userManager.FindByIdAsync(id);

            if (user == null)
            {
                return NotFound();
            }

            var roles = await _userManager.GetRolesAsync(user);

            var model = new AdminRegistroUsuarioEditViewModel
            {
                UserName = user.UserName,
                EmailRegister = user.Email,
                IsVendedor = roles.Contains(RolesTypes.Vendedor),
                IsGerente = roles.Contains(RolesTypes.Gerente),
                IsAdmin = roles.Contains(RolesTypes.Admin),
                IsDoador = roles.Contains(RolesTypes.AreaDoacao)
            };

            return View(model);
        }


        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(string id, AdminRegistroUsuarioEditViewModel model)
        {
            if (ModelState.IsValid)
            {
                var user = await _userManager.FindByIdAsync(id);

                if (user == null)
                {
                    return NotFound();
                }

                var userExists = await _userManager.FindByNameAsync(model.UserName);
                if (userExists != null && userExists.Id != user.Id)
                {
                    ModelState.AddModelError("", "Já existe um usuário com esse nome.");
                    return View(model);
                }

                userExists = await _userManager.FindByEmailAsync(model.EmailRegister);
                if (userExists != null && userExists.Id != user.Id)
                {
                    ModelState.AddModelError("", "Já existe um usuário com esse e-mail.");
                    return View(model);
                }

                user.Email = model.EmailRegister;
                user.UserName = model.UserName;

                if (!string.IsNullOrEmpty(model.GeneratedPassword))
                {
                    var passwordHasher = new PasswordHasher<IdentityUser>();
                    var passwordHash = passwordHasher.HashPassword(user, model.GeneratedPassword);
                    user.PasswordHash = passwordHash;
                }

                var result = await _userManager.UpdateAsync(user);

                if (result.Succeeded)
                {
                    var roles = await _userManager.GetRolesAsync(user);

                    await _userManager.RemoveFromRolesAsync(user, roles);

                    if (model.IsVendedor)
                    {
                        await _userManager.AddToRoleAsync(user, RolesTypes.Vendedor);
                    }
                    if (model.IsGerente)
                    {
                        await _userManager.AddToRoleAsync(user, RolesTypes.Gerente);
                    }
                    if (model.IsAdmin)
                    {
                        await _userManager.AddToRoleAsync(user, RolesTypes.Admin);
                    }
                    if (model.IsDoador)
                    {
                        await _userManager.AddToRoleAsync(user, RolesTypes.AreaDoacao);
                    }
                    return RedirectToAction(nameof(Index));
                }
                else
                {
                    foreach (var error in result.Errors)
                    {
                        ModelState.AddModelError("", error.Description);
                    }
                }
            }

            return View(model);
        }




        // GET: AdminFuncionariosController/Delete/5
        public async Task<IActionResult> Delete(string id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var user = await _userManager.FindByIdAsync(id);

            if (user == null)
            {
                return NotFound();

DonationAcademy/DonationAcademy/Areas/Admin/Views/AdminUsuarios/Create.cshtml
@model DonationAcademy.Areas.Admin.ViewModels.AdminRegistroUsuarioViewModel

@{
    ViewData["Title"] = "Adicionar Usuário";
}


<style>
    h1 {
        margin-top: 30px;
    }

    .row .form-group {
        margin-top: 20px;
    }

    .voltar a {
        color: white;
    }
</style>


<h1>Adicionar Usuário</h1>

<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            @*<div class="form-group">
                <label asp-for="Id" class="control-label"></label>
                <input asp-for="Id" class="form-control" />
                <span asp-validation-for="Id" class="text-danger"></span>
            </div>*@
            <div class="form-group">
                <label asp-for="UserName" class="control-label"></label>
                <input asp-for="UserName" class="form-control" />
                <span asp-validation-for="UserName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="EmailRegister" class="control-label"></label>
                <input asp-for="EmailRegister" class="form-control" />
                <span asp-validation-for="EmailRegister" class="text-danger"></span>
            </div>
            <div class="form-group form-check">
                <label class="form-check-label">
                    <input class="form-check-input" asp-for="IsVendedor" onchange="selectOnlyThis('vendedor')" id="vendedor" /> @Html.DisplayNameFor(model => model.IsVendedor)
                </label>
            </div>
            <div class="form-group form-check">
                <label class="form-check-label">
                    <input class="form-check-input" asp-for="IsGerente" onchange="selectOnlyThis('gerente')" id="gerente" /> @Html.DisplayNameFor(model => model.IsGerente)
                </label>
            </div>
            <div class="form-group form-check">
                <label class="form-check-label">
                    <input class="form-check-input" asp-for="IsAdmin" onchange="selectOnlyThis('admin')" id="admin" /> @Html.DisplayNameFor(model => model.IsAdmin)
                </label>
            </div>

            <div class="form-group form-check">
                <label class="form-check-label">
                    <input class="form-check-input" asp-for="IsDoador" onchange="selectOnlyThis('areadoacao')" id="areadoacao" /> @Html.DisplayNameFor(model => model.IsDoador)
                </label>
            </div>


            <div class="form-group">
                <label asp-for="GeneratedPassword" class="control-label"></label>
                <div class="input-group">
                    <input asp-for="GeneratedPassword" class="form-control" readonly required />
                    <div class="input-group-append">
                        <button id="btnGeneratePassword" type="button" class="btn btn-secondary">Gerar senha aleatória</button>
                    </div>
                </div>
                <span asp-validation-for="GeneratedPassword" class="text-danger"></span>
            </div>

            @section Scripts {
                <script>
                    $('#btnGeneratePassword').click(function () {
                        $.ajax({
                            url: '@Url.Action("GenerateRandomPassword", "AdminUsuarios")',
                            type: 'GET',
                            success: function (data) {
                                $('#GeneratedPassword').val(data);
                            }
                        });
                    });
                </script>

                <script>
                    const checkboxes = document.querySelectorAll('.form-check-input');

                    function selectOnlyThis(id) {
                        checkboxes.forEach((checkbox) => {
                            if (checkbox.id === id) {
                                if (checkbox.checked) {
                                    checkboxes.forEach((otherCheckbox) => {
                                        if (otherCheckbox !== checkbox) {
                                            otherCheckbox.checked = false;
                                        }
                                    });
                                }
                            }
                        });
                    }


                </script>

            }

            
            <div class="form-group">
                <input type="submit" value="Criar" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>
<script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>

<div class="voltar">
    <a asp-action="Index">Voltar</a>
</div>

DonationAcademy/DonationAcademy/Areas/Admin/Views/AdminUsuarios/Delete.cshtml
@model DonationAcademy.Areas.Admin.ViewModels.AdminRegistroUsuarioViewModel

@{
    ViewData["Title"] = "Excluir Usuário";
}


<h1>Excluir Usuário</h1>

<h3>Tem certeza que deseja excluir esse usuário?</h3>
<div>
    
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.UserName)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.UserName)
        </dd>
        @*<dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.EmailRegister)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.EmailRegister)
        </dd>*@
        @*<dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.IsVendedor)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.IsVendedor)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.IsGerente)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.IsGerente)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.IsAdmin)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.IsAdmin)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.IsDoador)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.IsDoador)
        </dd>*@
        @*<dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.GeneratedPassword)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.GeneratedPassword)
        </dd>*@
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="Id" />
        <input type="submit" value="Excluir" class="btn btn-danger" /> |
        <a asp-action="Index" style="color:white">Voltar</a>
    </form>
</div>

DonationAcademy/DonationAcademy/Areas/Admin/Views/AdminUsuarios/Details.cshtml
@model DonationAcademy.Areas.Admin.ViewModels.AdminRegistroUsuarioViewModel

@{
    ViewData["Title"] = "Detalhes do Usuário";
}


<style>
    h1 {
        margin-top: 30px;
    }

    .row .form-group {
        margin-top: 20px;
    }

</style>


<h1>Informações do Usuário</h1>

<div>
    
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.UserName)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.UserName)
        </dd>
        @*<dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.EmailRegister)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.EmailRegister)
        </dd>*@
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.IsVendedor)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.IsVendedor)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.IsGerente)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.IsGerente)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.IsAdmin)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.IsAdmin)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.IsDoador)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.IsDoador)
        </dd>
        @*<dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.GeneratedPassword)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.GeneratedPassword)
        </dd>*@

    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model?.Id" style="color:white">Editar</a> |
    <a asp-action="Index" style="color:white">Voltar</a>
</div>

DonationAcademy/DonationAcademy/Areas/Admin/Views/AdminUsuarios/Edit.cshtml
@model DonationAcademy.Areas.Admin.ViewModels.AdminRegistroUsuarioEditViewModel

@{
    ViewData["Title"] = "Editar Usuário";
}


<style>
    h1 {
        margin-top: 30px;
    }

    .row .form-group {
        margin-top: 20px;
    }

    .voltar a {
        color: white;
    }
</style>

<h1>Editar Usuário</h1>

<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="Id" />
            <div class="form-group">
                <label asp-for="UserName" class="control-label"></label>
                <input asp-for="UserName" class="form-control" />
                <span asp-validation-for="UserName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="EmailRegister" class="control-label"></label>
                <input asp-for="EmailRegister" class="form-control" />
                <span asp-validation-for="EmailRegister" class="text-danger"></span>
            </div>
            <div class="form-group form-check">
                <label class="form-check-label">
                    <input class="form-check-input" asp-for="IsVendedor" onchange="selectOnlyThis('vendedor')" id="vendedor" /> @Html.DisplayNameFor(model => model.IsVendedor)
                </label>
            </div>
            <div class="form-group form-check">
                <label class="form-check-label">
                    <input class="form-check-input" asp-for="IsGerente" onchange="selectOnlyThis('gerente')" id="gerente" /> @Html.DisplayNameFor(model => model.IsGerente)
                </label>
            </div>
            <div class="form-group form-check">
                <label class="form-check-label">
                    <input class="form-check-input" asp-for="IsAdmin" onchange="selectOnlyThis('admin')" id="admin" /> @Html.DisplayNameFor(model => model.IsAdmin)
                </label>
            </div>
            <div class="form-group form-check">
                <label class="form-check-label">
                    <input class="form-check-input" asp-for="IsDoador" onchange="selectOnlyThis('areadoacao')" id="areadoacao" /> @Html.DisplayNameFor(model => model.IsDoador)
                </label>
            </div>

            <div class="form-group">
                <label asp-for="GeneratedPassword" class="control-label"></label>
                <div class="input-group">
                    <input asp-for="GeneratedPassword" class="form-control" readonly />
                    <div class="input-group-append">
                        <button id="btnGeneratePasswordEdit" type="button" class="btn btn-secondary">Resetar senha</button>
                    </div>
                </div>
                <span asp-validation-for="GeneratedPassword" class="text-danger"></span>
            </div>

            @section Scripts {
                <script>
                    $('#btnGeneratePasswordEdit').click(function () {
                        $.ajax({
                            url: '@Url.Action("GenerateRandomPassword", "AdminUsuarios")',
                            type: 'GET',
                            success: function (data) {
                                $('#GeneratedPassword').val(data);
                            }
                        });
                    });
                </script>

                <script>
                    const checkboxes = document.querySelectorAll('.form-check-input');

                    function selectOnlyThis(id) {
                        checkboxes.forEach((checkbox) => {
                            if (checkbox.id === id) {
                                if (checkbox.checked) {
                                    checkboxes.forEach((otherCheckbox) => {
                                        if (otherCheckbox !== checkbox) {
                                            otherCheckbox.checked = false;
                                        }
                                    });
                                }
                            }
                        });
                    }


                </script>
            }

            <div class="form-group">
                <input type="submit" value="Salvar" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>

<div class="voltar">
    <a asp-action="Index">Voltar</a>
</div>

DonationAcademy/DonationAcademy/Areas/Admin/Views/AdminUsuarios/Index.cshtml
@model ReflectionIT.Mvc.Paging.PagingList<DonationAcademy.Areas.Admin.ViewModels.AdminRegistroUsuarioViewModel>

@{
    ViewData["Title"] = "Gerenciar usuários";
}

<style>
    h3 {
        margin-top: 30px;
    }

    th, tr, a {
        color: white;
    }
</style>

<h3>Gerenciamento de Usuários</h3>



<form method="get" class="form-inline">

    <input name="filter" class="form-control" placeholder="filtro"
           value="@Model.RouteValue["Filter"]" />

    <br />

    <button type="submit" class="btn btn-info">

        <span class="glyphicon glyphicon-search" aria-hidden="true"></span> Procurar

    </button>

</form>

<br />

Total de Usuários: @Model.TotalRecordCount

<br />

@await this.Component.InvokeAsync("Pager", new { pagingList = this.Model })


<p>
    <a asp-action="Create">Adicionar usuário</a>
</p>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.UserName)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.EmailRegister)
            </th>
            @*<th>
                @Html.DisplayNameFor(model => model.IsVendedor)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.IsGerente)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.IsAdmin)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.IsDoador)
            </th>*@
            @*<th>
                @Html.DisplayNameFor(model => model.GeneratedPassword)
            </th>*@

           <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.UserName)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.EmailRegister)
            </td>
            @*<td>
                @Html.DisplayFor(modelItem => item.IsVendedor)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.IsGerente)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.IsAdmin)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.IsDoador)
            </td>*@
           @* <td>
                @Html.DisplayFor(modelItem => item.GeneratedPassword)
            </td>*@
            
            <td>
                <a asp-action="Edit" asp-route-id="@item.Id">Editar</a> |
                <a asp-action="Details" asp-route-id="@item.Id">Detalhes</a> |
                <a asp-action="Delete" asp-route-id="@item.Id">Deletar</a>
            </td>
        </tr>
}
    </tbody>
</table>